<?php

namespace GraphQL\SchemaObject;

use GraphQL\Exception\EmptySelectionSetException;
use GraphQL\Query;

/**
 * An abstract class that acts as the base for all schema query objects generated by the SchemaScanner
 *
 * Class QueryObject
 *
 * @package GraphQL\SchemaObject
 */
abstract class QueryObject
{
    /**
     * This constant stores the name of the object name in the API definition
     *
     * @var string
     */
    private const OBJECT_NAME = '';

    /**
     * This string attribute stores the name alias to be used in queries for this object
     *
     * @var string
     */
    private $nameAlias;

    /**
     * This array stores the set of selected fields' names for this object
     *
     * @var array
     */
    private $selectionSet;

    /**
     * SchemaObject constructor.
     *
     * @param string $nameAlias
     */
    public function __construct($nameAlias = '')
    {
        $this->selectionSet = [];
        $this->nameAlias    = !empty($nameAlias) ? $nameAlias : static::OBJECT_NAME;
    }

    /**
     * @return Query
     * @throws EmptySelectionSetException
     */
	protected function toQuery(): Query
	{
        if (empty($this->selectionSet)) {
            throw new EmptySelectionSetException(static::class);
        }

        // Convert nested query objects to string queries
        $argumentsList = $this->constructArgumentsList();
        foreach ($this->selectionSet as $key => $field) {
            if ($field instanceof QueryObject) {
                $this->selectionSet[$key] = $field->toQuery();
            }
        }

        // Create and return query for this object
        $query = new Query($this->nameAlias);
        $query->setArguments($argumentsList);
        $query->setSelectionSet($this->selectionSet);

        return $query;
	}

    /**
     * Constructs the object's arguments list from its attributes
     */
	protected function constructArgumentsList(): array
    {
        $argumentsList = [];
        foreach ($this as $name => $value) {
            // TODO: Use annotations to avoid having to check on specific keys
            if (empty($value) || in_array($name, ['nameAlias', 'selectionSet'])) continue;

            // Handle input objects before adding them to the arguments list
            if ($value instanceof InputObject) {
                $value = $value->toRawObject();
            }

            $argumentsList[$name] = $value;
        }

        return $argumentsList;
    }

    /**
     * @param string|QueryObject $selectedField
     */
	protected function selectField($selectedField): void
    {
        if (is_string($selectedField) || $selectedField instanceof QueryObject) {
            $this->selectionSet[] = $selectedField;
        }
    }

    /**
     * @return string
     * @throws EmptySelectionSetException
     */
    public function getQueryString(): string
    {
        return (string) $this->toQuery();
    }
}