<?php
/**
 * Created by PhpStorm.
 * User: mostafa
 * Date: 1/18/19
 * Time: 12:47 AM
 */

namespace GraphQL\SchemaObject;

use GraphQL\Query;

/**
 * An abstract class that acts as the base for all schema query objects generated by the SchemaScanner
 *
 * Class QueryObject
 *
 * @package GraphQL\SchemaObject
 */
abstract class QueryObject
{
    /**
     * This constant stores the name of the object name in the API definition
     *
     * @var string
     */
    const OBJECT_NAME = '';

    /**
     * This array stores the set of selected fields' names for this object
     *
     * @var array
     */
    private $selectionSet;

    /**
     * This array stores a map of argument name to argument value for this object
     *
     * @var array
     */
    private $arguments;

    /**
     * @var int
     */
    protected $first;

    /**
     * @var int
     */
    protected $offset;

    /**
     * SchemaObject constructor.
     */
    public function __construct()
    {
        $this->selectionSet = [];
        $this->arguments    = [];
    }

    /**
	 * @return Query
	 */
	protected function toQuery()
	{
	    // Construct arguments list
        $this->constructArguments();

        // Create and return query for this object
        $query = new Query(static::OBJECT_NAME);
        $query->setArguments($this->arguments);
        $query->setSelectionSet($this->selectionSet);

        return $query;
	}

    /**
     * Constructs the object's arguments list from its attributes
     */
	protected function constructArguments()
    {
        foreach ($this as $name => $value) {
            if (!is_array($value) && !is_object($value) && !empty($value)) {
                $this->arguments[$name] = $value;
            }
        }
    }

    /**
     * @param $fieldName
     */
	protected function selectField($fieldName)
    {
        $this->selectionSet[] = $fieldName;
    }

    /**
     * @param int $firstObjects
     *
     * @return $this
     */
    public function setFirst($firstObjects)
    {
        $this->first = $firstObjects;

        return $this;
    }

    /**
     * @param int $offsetObjects
     *
     * @return $this
     */
    public function setOffset($offsetObjects)
    {
        $this->offset = $offsetObjects;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string) $this->toQuery();
    }
}